### PR TITLE
resolves #448 and fixing uploading avatar image resolves #449

### LINKED ISSUE #448: Jorge Issues
- [x] Remove rangerzone if enterprise
- [x] Event parser parse domain from event
- [x] Highlight selected rows

### LINKED ISSUE #449: Uploading Avatar Image
- Avatar Image is not being uploaded

### PR DESCRIPTION
**Pull request by Hirobreak**
- Removing danger zone if enterprise account
- Parse event domain with new event
- Uploading avatar fixed
- Request Manager account id fix
- Highlight mailbox cells on touch

### CODE REVIEW

File: iOS-Email-Client/Controllers/ProfileEditorViewController.swift [hunk 1]
```diff
@@ -64,44 +64,38 @@ class ProfileEditorViewController: UIViewController {
...
+    @IBOutlet weak var scrollContentViewHeightConstraint: NSLayoutConstraint!
+    @IBOutlet weak var tableViewHeightConstraint: NSLayoutConstraint!
     let STATUS_NOT_CONFIRMED = 0
     let SECTION_PROFILE = 0
-    let ROW_HEIGHT: CGFloat = 40.0
+    let ROW_HEADER_HEIGHT: CGFloat = 40.0
+    let ROW_HEIGHT: CGFloat = 60.0
     var imagePicker = UIImagePickerController()
-    var attachmentOptionsHeight: CGFloat = 0
+    var attachmentOptionsBottomPadding: CGFloat = -120
```
Comment (jorgeblacio) [inline iOS-Email-Client/Controllers/ProfileEditorViewController.swift]: If this is a constant, should be with the same format as others.
`var ATTACHMENT_OPTIONS_BOTTOM_PADDING: CGFloat = -120`
